"""Initial schema — sessions, PTT, entities, decision audit log.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-03

Hand-written rather than autogenerated so the project ships with a real
migration history from day one. Future model changes should run:

    alembic revision --autogenerate -m "<change>"

Mirrors `memory/models.py` exactly. Targets PostgreSQL (the default in
docker-compose.yml). On Postgres, `JsonCol` resolves to JSONB; on SQLite
it falls back to JSON, but Alembic targeting Postgres is what we care about.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


# ────────────────────────────────────────────────────────────────────────────
# Enum types — defined as Postgres ENUMs so Alembic can drop them on rollback
# ────────────────────────────────────────────────────────────────────────────

attack_phase = sa.Enum(
    "recon", "enumeration", "vuln_id", "exploitation",
    "post_exploit", "lateral_movement", "objective",
    name="attackphase",
)
node_status = sa.Enum(
    "pending", "in_progress", "completed", "failed", "skipped",
    "awaiting_approval", "rejected",
    name="nodestatus",
)
session_status = sa.Enum(
    "initialising", "running", "paused", "completed", "aborted", "error",
    name="sessionstatus",
)
operation_mode = sa.Enum(
    "autonomous", "human_in_loop",
    name="operationmode",
)


def upgrade() -> None:
    bind = op.get_bind()
    attack_phase.create(bind, checkfirst=True)
    node_status.create(bind, checkfirst=True)
    session_status.create(bind, checkfirst=True)
    operation_mode.create(bind, checkfirst=True)

    # ─── pentest_sessions ────────────────────────────────────────────────
    op.create_table(
        "pentest_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("target", sa.String(500), nullable=False),
        sa.Column("environment", sa.String(50), nullable=False),
        sa.Column("mode", operation_mode, nullable=False),
        sa.Column("status", session_status, nullable=False,
                  server_default="initialising"),
        sa.Column("objective", sa.Text()),
        sa.Column("rules_of_engagement", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("started_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime()),
    )
    op.create_index(
        "ix_pentest_sessions_started_at",
        "pentest_sessions", ["started_at"], unique=False,
    )

    # ─── task_nodes (PTT) ────────────────────────────────────────────────
    op.create_table(
        "task_nodes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("pentest_sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("task_nodes.id", ondelete="CASCADE")),
        sa.Column("blocked_by_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("task_nodes.id", ondelete="SET NULL")),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("rationale", sa.Text()),
        sa.Column("phase", attack_phase, nullable=False),
        sa.Column("mitre_ttp", sa.String(50)),
        sa.Column("status", node_status, nullable=False,
                  server_default="pending"),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="3"),
        sa.Column("depth", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("target", sa.String(500)),
        sa.Column("tool_name", sa.String(100)),
        sa.Column("tool_params", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("command", sa.Text()),
        sa.Column("raw_output", sa.Text()),
        sa.Column("findings", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("started_at", sa.DateTime()),
        sa.Column("completed_at", sa.DateTime()),
    )
    op.create_index("ix_task_nodes_session_id", "task_nodes", ["session_id"])
    op.create_index("ix_task_nodes_parent_id", "task_nodes", ["parent_id"])
    op.create_index("ix_task_nodes_status", "task_nodes", ["status"])
    op.create_index(
        "ix_task_nodes_session_status_priority",
        "task_nodes", ["session_id", "status", "priority"],
    )

    # ─── hosts ───────────────────────────────────────────────────────────
    op.create_table(
        "hosts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("pentest_sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("ip", sa.String(45), nullable=False),
        sa.Column("hostname", sa.String(255)),
        sa.Column("os_fingerprint", sa.String(255)),
        sa.Column("ports", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("services", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("is_compromised", sa.Boolean(), nullable=False,
                  server_default=sa.false()),
        sa.Column("notes", sa.Text()),
        sa.Column("discovered_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_hosts_session_id", "hosts", ["session_id"])
    op.create_index("ix_hosts_session_ip", "hosts", ["session_id", "ip"], unique=True)

    # ─── vulnerabilities ─────────────────────────────────────────────────
    op.create_table(
        "vulnerabilities",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("pentest_sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("host_ip", sa.String(45), nullable=False),
        sa.Column("port", sa.Integer()),
        sa.Column("service", sa.String(100)),
        sa.Column("cve", sa.String(50)),
        sa.Column("cvss", sa.Float()),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("evidence", sa.Text()),
        sa.Column("mitre_ttp", sa.String(50)),
        sa.Column("exploited", sa.Boolean(), nullable=False,
                  server_default=sa.false()),
        sa.Column("discovered_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_vulnerabilities_session_id", "vulnerabilities", ["session_id"])
    op.create_index("ix_vulnerabilities_severity", "vulnerabilities", ["severity"])
    op.create_index("ix_vulnerabilities_cve", "vulnerabilities", ["cve"])

    # ─── credentials ─────────────────────────────────────────────────────
    op.create_table(
        "credentials",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("pentest_sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("host_ip", sa.String(45)),
        sa.Column("service", sa.String(100)),
        sa.Column("username", sa.String(255), nullable=False),
        sa.Column("secret", sa.String(1000), nullable=False),
        sa.Column("secret_type", sa.String(50), nullable=False),
        sa.Column("domain", sa.String(255)),
        sa.Column("privilege", sa.String(50)),
        sa.Column("obtained_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_credentials_session_id", "credentials", ["session_id"])

    # ─── agent_decisions (FYP §8.1 audit log) ────────────────────────────
    op.create_table(
        "agent_decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("pentest_sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("task_node_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("task_nodes.id", ondelete="SET NULL")),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("context", postgresql.JSONB(), nullable=False),
        sa.Column("proposed_action", postgresql.JSONB(), nullable=False),
        sa.Column("actual_command", sa.Text()),
        sa.Column("result_summary", postgresql.JSONB(),
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("approved_by", sa.String(100)),
        sa.Column("llm_model", sa.String(100)),
        sa.Column("llm_input_tokens", sa.Integer()),
        sa.Column("llm_output_tokens", sa.Integer()),
        sa.Column("created_at", sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index(
        "ix_agent_decisions_session_step",
        "agent_decisions", ["session_id", "step_number"],
    )


def downgrade() -> None:
    op.drop_index("ix_agent_decisions_session_step", table_name="agent_decisions")
    op.drop_table("agent_decisions")

    op.drop_index("ix_credentials_session_id", table_name="credentials")
    op.drop_table("credentials")

    op.drop_index("ix_vulnerabilities_cve", table_name="vulnerabilities")
    op.drop_index("ix_vulnerabilities_severity", table_name="vulnerabilities")
    op.drop_index("ix_vulnerabilities_session_id", table_name="vulnerabilities")
    op.drop_table("vulnerabilities")

    op.drop_index("ix_hosts_session_ip", table_name="hosts")
    op.drop_index("ix_hosts_session_id", table_name="hosts")
    op.drop_table("hosts")

    op.drop_index("ix_task_nodes_session_status_priority", table_name="task_nodes")
    op.drop_index("ix_task_nodes_status", table_name="task_nodes")
    op.drop_index("ix_task_nodes_parent_id", table_name="task_nodes")
    op.drop_index("ix_task_nodes_session_id", table_name="task_nodes")
    op.drop_table("task_nodes")

    op.drop_index("ix_pentest_sessions_started_at", table_name="pentest_sessions")
    op.drop_table("pentest_sessions")

    bind = op.get_bind()
    operation_mode.drop(bind, checkfirst=True)
    session_status.drop(bind, checkfirst=True)
    node_status.drop(bind, checkfirst=True)
    attack_phase.drop(bind, checkfirst=True)
